# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdc00da5daa21f4a3cc78797c88278b77b0c2c34cbb111810bfd71780a531b606f40d922efb2252ac999084cf0dc86be004e683eff3214913339618f30bd26b7

test:
  secret_key_base: 184ce69ece78b5ef37cedf86084c094fbb72c184be8c50efac4324b5a923f8feeb572e6098b53a5906cbbc33823728ed6dec3247ad192eb3e90c9c0003797f8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
